name: Build

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
    paths:
      - ".github/workflows/build.yml"
      - "Bottomless/**"
      - "Bottomless.xcodeproj/**"

jobs:
  build:
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Switch version of Xcode
        run: sudo xcode-select --switch "/Applications/Xcode_12.app/Contents/Developer"

      - name: Build
        run: set -o pipefail && xcodebuild clean build -project Bottomless.xcodeproj -scheme Bottomless -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcpretty --simple
